### ISSUE TITLE
add output for lane-changing related information (trac #1441)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#1441]
currently, the only way to get information regarding lane changes is to parse the netstate-dump (or the similar fcd-output). This is 
* expensive as a lot of data has to be written and parsed
* incomplete, since it is not easily discernible whether moving to another lane on a different edge was done by lane changing or by using a direct connection.

1) output of executed lane changes each time step (only for vehicles that changed)
2) optionally output of lane changing state for each vehicle and time step
3) optionally state with and without TraCI influence

Migrated from http://sumo.dlr.de/ticket/1441
```json
{
    "status": "new", 
    "changetime": "2015-01-04T23:02:08Z", 
    "description": "currently, the only way to get information regarding lane changes is to parse the netstate-dump (or the similar fcd-output). This is \n* expensive as a lot of data has to be written and parsed\n* incomplete, since it is not easily discernible whether moving to another lane on a different edge was done by lane changing or by using a direct connection.\n\n1) output of executed lane changes each time step (only for vehicles that changed)\n2) optionally output of lane changing state for each vehicle and time step\n3) optionally state with and without TraCI influence\n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1420412528364389", 
    "component": "simulation data output", 
    "summary": "add output for lane-changing related information", 
    "priority": "major", 
    "keywords": "", 
    "time": "2014-09-16T12:01:18Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
implemented xml output and traci access some time ago
