### ISSUE TITLE
allow creation/modification of POIs and Polygons (trac #1667)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#1667]
**Functionality**:

- ☑ New netedit mode POI/Polygon (Hotkey 'P')
- ☑ In GNEShapeFrame switch between POI/Polygon (similar to GNEAdditionalFrame)
- ☑ Create pois on click (at click location) with current attributes (add #INDEX to avoid duplicate ids)
- ☑ Create new Polygons with multiple clicks:
* ☑ User be able to create Polygons clicking with left button over the viewNet. Every click creates a polygon's vertice that is automatically connected with the last created vertice.
* ☑ Clicks can be snapped to grid.
* ☑ Press ESC key abort creation of current polygon.
* ☑ Right button remove last created vertice.
* ☑ Color of polygon can be changed at creation or through inspect mode.
- ☑ Shape of polygon can be Blocked.
- ☑ Movement of polygon can be Blocked.
- ~~Coordinates of polygon can be interpreted as geo-coordinates before saving through a question dialog.~~
- ☑ Longitude and Latitude coordinates will be merged as GEO Position.
- ☑ Point Of interest over lanes will be implemented ni a new clase called POILane
- ~~If GeoConvHelper::usingGeoProjection() is disabled, GEO Options Box in inspector frame will be disabled~~
- ☑ Support for opening/closing Polygons:
* ☑ Shaped of closed polygons starts and end in the same point.
* ☑ Polygon frame muss allow to create closed polygons.
* ☑ Inspector frame must have a checkBox to close/open polygons.
- ☑ Support for merge vertices:
* ☑ Moving polygon's vertice to another adjacent vertice must merge both vertices. 
* ☑ Moving the end point to the start point (and viceversa) must close the polygon.
- ☑Shapes can be grouped using Select mode
* ☑Set of Polygons can be inspected and moved together.
* ☑Set of POIs can be inspected and moved together.
* ☑GNEPolygons are moved always as "blocked shapes".
* ☑ Selected Shapes can be removed using DEL hotkey in delete mode.
- ☑ Contextual menu:
* ☑ Simplify Shape (convert it to a Square)
* ☑ If shape is closed: Open polygon.
* ☑ If shape is opened: Close polygon.
* ☑ Over a vertice: remove vertice.
* ☑ Over a vertice: give the option of convert it in the first Vertice (This "rotate" the polygon without changing their shape's points)
* ☑ Over a POI over lane: Transform into a POILane.
* ☑ Over a POILane: Transform into a POI.

**Non-Functionality**:

- ~~Polygon's areas cannot be empty~~
- ~~Polygons has to have always at least three diferent points in their shape.~~
- ☑ A polygon cannot own two consecutive points with the same coordinates, or with a distance between both minor that 0.8.
- ☑ Positions of POIs must be virtual attributes.
- ☑ If user changes the ortogonal position of Shape or POI, geo positions must change (And vice versa)
- In POIs, if a Lane and Position Over Lane is Specified, ortogonal and Geo position must change.
- ☑ Over Start and end points of polygon must be drawed the letter "S" and "E".
- ☑ If vertices's merging results in an invalid polygon, last vertice movement has to be canceled, and shape must be restored to their original position before moving.

**Prerequisites**:

* ☑ #3232: Implements GNEChange_Poly 
* ☑ #2744: Implements GNEChange_POI
* ☑ #3234: Implement GNEPolygonFrame

**Related**
- #3334: Advanced shape manipulation
- ☑ #2501: Add delete-mode check-box 'delete only geometry points'

**Problems**
- ☑ Crash setting a invalid color (ex: "Vlue") in POIs and Polys. Related: #3235

Migrated from http://sumo.dlr.de/ticket/1667
```json
{
    "status": "assigned", 
    "changetime": "2017-10-18T12:02:58Z", 
    "description": "'''Functionality''':\n\n- \u2611 New netedit mode POI/Polygon (Hotkey 'P')\n- \u2611 In GNEShapeFrame switch between POI/Polygon (similar to GNEAdditionalFrame)\n- \u2611 Create pois on click (at click location) with current attributes (add #INDEX to avoid duplicate ids)\n- \u2611 Create new Polygons with multiple clicks:\n - \u2611 User be able to create Polygons clicking with left button over the viewNet. Every click creates a polygon's vertice that is automatically connected with the last created vertice.\n - \u2611 Clicks can be snapped to grid.\n - \u2611 Press ESC key abort creation of current polygon.\n - \u2611 Right button remove last created vertice.\n - \u2611 Color of polygon can be changed at creation or through inspect mode.\n- \u2611 Shape of polygon can be Blocked.\n- \u2611 Movement of polygon can be Blocked.\n- ~~Coordinates of polygon can be interpreted as geo-coordinates before saving through a question dialog.~~\n- \u2611 Longitude and Latitude coordinates will be merged as GEO Position.\n- \u2611 Point Of interest over lanes will be implemented ni a new clase called POILane\n- If GeoConvHelper::usingGeoProjection() is disabled, GEO Options Box in inspector frame will be disabled\n- \u2611 Support for opening/closing Polygons:\n - \u2611 Shaped of closed polygons starts and end in the same point.\n - \u2611 Polygon frame muss allow to create closed polygons.\n - \u2611 Inspector frame must have a checkBox to close/open polygons.\n- \u2611 Support for merge vertices:\n - \u2611 Moving polygon's vertice to another adjacent vertice must merge both vertices. \n - \u2611 Moving the end point to the start point (and viceversa) must close the polygon.\n- Shapes can be grouped using Select mode\n - Set of Polygons can be inspected and moved together.\n - Set of POIs can be inspected and moved together.\n - GNEPolygons are moved always as \"blocked shapes\".\n - \u2611 Selected Shapes can be removed using DEL hotkey in delete mode.\n- \u2611 Contextual menu:\n - \u2611 Simplify Shape (convert it to a Square)\n - \u2611 If shape is closed: Open polygon.\n - \u2611 If shape is opened: Close polygon.\n - \u2611 Over a vertice: remove vertice.\n - \u2611 Over a vertice: give the option of convert it in the first Vertice (This \"rotate\" the polygon without changing their shape's points)\n - Over a POI over lane: Transform into a POILane.\n - Over a POILane: Transform into a POI.\n\n\n'''Non-Functionality''':\n\n- ~~Polygon's areas cannot be empty~~\n- ~~Polygons has to have always at least three diferent points in their shape.~~\n- \u2611 A polygon cannot own two consecutive points with the same coordinates, or with a distance between both minor that 0.8.\n- \u2611 Positions of POIs must be virtual attributes.\n- \u2611 If user changes the ortogonal position of Shape or POI, geo positions must change (And vice versa)\n- In POIs, if a Lane and Position Over Lane is Specified, ortogonal and Geo position must change.\n- \u2611 Over Start and end points of polygon must be drawed the letter \"S\" and \"E\".\n- \u2611 If vertices's merging results in an invalid polygon, last vertice movement has to be canceled, and shape must be restored to their original position before moving.\n\n\n'''Prerequisites''':\n\n - \u2611 #3232: Implements GNEChange_Poly \n - \u2611 #2744: Implements GNEChange_POI\n - \u2611 #3234: Implement GNEPolygonFrame\n\n'''Related'''\n- #3334: Advanced shape manipulation\n- #2501: Add delete-mode check-box 'delete only geometry points'\n\n'''Problems'''\n- \u2611 Crash setting a invalid color (ex: \"Vlue\") in POIs and Polys. Related: #3235\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1508328178577102", 
    "component": "netedit", 
    "summary": "allow creation/modification of POIs and Polygons", 
    "priority": "major", 
    "keywords": "GNEPOI, GNEPoly", 
    "time": "2015-03-09T07:32:22Z", 
    "milestone": "1.0.0", 
    "owner": "pablo", 
    "type": "enhancement"
}
```

**Comment by palvarezlopez** [comment]
I think that its better to have always enabled the GEO Option Box instead of GeoConvHelper::usingGeoProjection(). This option can be used only during saving shapes.
