### ISSUE TITLE
switching a traffic light off should invalidate cont-links from minor roads (trac #1676)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#1676]
a traffic light potentially has cont-links and internal junctions from all directions. When switching the traffic light off, the junction turns into a priority junction where only the main direction is allowed to wait on the junction. Currently this does not happen and all directions wait on the junction.

Depends on #1484 to detect the main direction.

Migrated from http://sumo.dlr.de/ticket/1676
```json
{
    "status": "new", 
    "changetime": "2015-08-21T11:04:56Z", 
    "description": "a traffic light potentially has cont-links and internal junctions from all directions. When switching the traffic light off, the junction turns into a priority junction where only the main direction is allowed to wait on the junction. Currently this does not happen and all directions wait on the junction.\n\nDepends on #1484 to detect the main direction.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1440155096333820", 
    "component": "microsim - junctions", 
    "summary": "switching a traffic light off should invalidate cont-links from minor roads", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-03-12T06:15:45Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
this is related to #1844: The solution for #1844 is to modify the response matrix so that the major direction also yields to vehicles on the minor cont-lane. However, without switching fixing #1676 and #1484 this would result in deadlock.
