### ISSUE TITLE
Eletric model isn't compatible with old SUMO versions (trac #2635)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#2635]
Originally, electric model in SUMO had the parameters "ActBatKap" und "MaxBatKap". In the last version was changed to "actualBatteryCapacity" and "maximumBatteryCapacity". This provoked, that the first SUMO simulations that used the old names don't write the output values in the battery file.

Task: Implementation of Synontms for "ActBatKap" -> "actualBatteryCapacity" and  "MaxBatKap" -> "maximumBatteryCapacity"

Migrated from http://sumo.dlr.de/ticket/2635
```json
{
    "status": "new", 
    "changetime": "2017-08-21T21:29:58Z", 
    "description": "Originally, electric model in SUMO had the parameters \"ActBatKap\" und \"MaxBatKap\". In the last version was changed to \"actualBatteryCapacity\" and \"maximumBatteryCapacity\". This provoked, that the first SUMO simulations that used the old names don't write the output values in the battery file.\n\nTask: Implementation of Synontms for \"ActBatKap\" -> \"actualBatteryCapacity\" and  \"MaxBatKap\" -> \"maximumBatteryCapacity\"", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1503350998933744", 
    "component": "simulation data output", 
    "summary": "Eletric model isn't compatible with old SUMO versions", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-11-01T08:38:43Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
not relevant anymore

**Comment by Gvishnu1993** [comment]
Could you please share the EV charging station Source Code
Email : VishnuVardhanReddy.Guraka@in.bosch.com

**Comment by namdre** [comment]
see 
https://github.com/eclipse/sumo/blob/master/src/microsim/trigger/MSChargingStation.cpp
https://github.com/eclipse/sumo/blob/73f23accf150009f140799f6bd4b775084611d69/src/microsim/devices/MSDevice_Battery.cpp#L130
