### ISSUE TITLE
persons miss the bus (trac #2856)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#2856]
the router assumes that pedestrians will travel with their maxSpeed. This gives no safety buffer for delays when trying to catch a bus. Typical delays:
- time to travel across an intersection (internal edges are ignored by the router)
- waiting at crossings
- delays due to other pedestrians / jamming

Suggested solution:
- new <personTrip>-attribute '''walkingFactor''' that gives a factor on maxSpeed (i.e. 0.9) for computing walking times
- new duarouter-attribute to set a default value for this attribute

Migrated from http://sumo.dlr.de/ticket/2856
```json
{
    "status": "closed", 
    "changetime": "2017-02-10T14:45:36Z", 
    "description": "the router assumes that pedestrians will travel with their maxSpeed. This gives no safety buffer for delays when trying to catch a bus. Typical delays:\n- time to travel across an intersection (internal edges are ignored by the router)\n- waiting at crossings\n- delays due to other pedestrians / jamming\n\nSuggested solution:\n- new <personTrip>-attribute '''walkingFactor''' that gives a factor on maxSpeed (i.e. 0.9) for computing walking times\n- new duarouter-attribute to set a default value for this attribute", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1486737936595544", 
    "component": "microsim - intermodal", 
    "summary": "persons miss the bus", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-02-09T14:40:53Z", 
    "milestone": "0.29.0", 
    "owner": "namdre", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
in the web wizard scenario, average person speed is closer to 0.7 of maxSpeed for some persons (causing aborted rides). Maybe the default value of --persontrip.walkfactor should be lowered.

**Comment by namdre** [comment]
persons miss their connecting train when the first train is delayed (i.e. because it's insertion is delayed by other trains blocking the trainStop). This may happen when using option --random-begin because the schedule-generating simulation starts all trains at 0 creating a potential inconsistency.
