### ISSUE TITLE
Accel Keys must works under linux with Caps Lock enabled (trac #3188)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#3188]
Currently Accel Keys don't work under linux if Caps Locks is enabled.

'''Question:'''

  ''Hi Developers,''

  ''I have found a Bug under Linux related with Caps Lock key and Accel keys. If I define a Accel key using:''

  ''getAccelTable()->addAccel(parseAccel("a"), this, FXSEL(SEL_COMMAND, ObjectID>));''

  ''Under Windows works with Caps Lock key activated or deactivated, but under Linux only works if Caps Lock is deactivated, due with Caps Lock activated detects key "A" instead "a".  We have reproduced this bug under Ubuntu, Fedora and SUSE, In both 32 and 64 bits versions.''

'''Answer:'''

  Thanks for the info.

  But technically, the modifier keys are part of the accelerator, so the Alt+Key is *supposed* to be different from Alt+Shift+Key.

'''UPDATE:'''

Caps lock are provoking errors in almost every netedit test under '''Linux''', because caps lock is enabled before every test, and that provoke a malfunction in Key Modes (Inspect, Edge, Selection, etc.). It's a priority to fix it.

Migrated from http://sumo.dlr.de/ticket/3188
```json
{
    "status": "assigned", 
    "changetime": "2017-07-31T09:02:11Z", 
    "description": "Currently Accel Keys don't work under linux if Caps Locks is enabled.\n\n'''Question:'''\n\n  ''Hi Developers,''\n\n  ''I have found a Bug under Linux related with Caps Lock key and Accel keys. If I define a Accel key using:''\n\n  ''getAccelTable()->addAccel(parseAccel(\"a\"), this, FXSEL(SEL_COMMAND, ObjectID>));''\n\n  ''Under Windows works with Caps Lock key activated or deactivated, but under Linux only works if Caps Lock is deactivated, due with Caps Lock activated detects key \"A\" instead \"a\".  We have reproduced this bug under Ubuntu, Fedora and SUSE, In both 32 and 64 bits versions.''\n\n'''Answer:'''\n\n  Thanks for the info.\n\n  But technically, the modifier keys are part of the accelerator, so the Alt+Key is *supposed* to be different from Alt+Shift+Key.\n\n\n'''UPDATE:'''\n\nCaps lock are provoking errors in almost every netedit test under '''Linux''', because caps lock is enabled before every test, and that provoke a malfunction in Key Modes (Inspect, Edge, Selection, etc.). It's a priority to fix it.", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1501491731594880", 
    "component": "netedit", 
    "summary": "Accel Keys must works under linux with Caps Lock enabled", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2017-06-13T09:01:58Z", 
    "milestone": "1.1.0", 
    "owner": "pablo", 
    "type": "defect"
}
```

**Comment by palvarezlopez** [comment]
Fixed in b40198f78551093baed814483449277c77df327d
