### ISSUE TITLE
smartDB network building broken (trac #3222)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#3222]
since [7f952fc](../commit/7f952fce93a7bc8c5069bb093d5f5aa7601e73a4) (aka r24733) it gives

 Warning: Environment variable SUMO_HOME is not set, schema resolution will use slow website lookups.
 Warning: Given openDrive file 'SmartDB.2011.xodr' uses version 1.1;
 Version 1.2 is supported.
 Warning: Mismatched geometry for edge '2' between geometry segments 0 and 1.
 Warning: Mismatched geometry for edge '2' between geometry segments 1 and 2.
 Warning: Could not compute spiral geometry for edge '980' (Could not compute biarc parameters).
 Error: Could not add node '1006.224.29'.
 Quitting (on error).

It seems to be a floating point issue because it does not fail consistently in all three tests on all platforms

Migrated from http://sumo.dlr.de/ticket/3222
```json
{
    "status": "new", 
    "changetime": "2017-06-20T14:11:28Z", 
    "description": "since [24733] it gives\n\n Warning: Environment variable SUMO_HOME is not set, schema resolution will use slow website lookups.\n Warning: Given openDrive file 'SmartDB.2011.xodr' uses version 1.1;\n Version 1.2 is supported.\n Warning: Mismatched geometry for edge '2' between geometry segments 0 and 1.\n Warning: Mismatched geometry for edge '2' between geometry segments 1 and 2.\n Warning: Could not compute spiral geometry for edge '980' (Could not compute biarc parameters).\n Error: Could not add node '1006.224.29'.\n Quitting (on error).\n\nIt seems to be a floating point issue because it does not fail consistently in all three tests on all platforms\n", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1497967888330556", 
    "component": "scenarios", 
    "summary": "smartDB network building broken", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-06-20T14:04:22Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
fixed some time ago
