### ISSUE TITLE
Netedit crashes on delete

### ISSUE THREAD

**Issue by vtalpaert** [DLR-TS/sumo#3564]
Hi, I encountered a bug where Netedit crashes using the erasing tool

Steps to reproduce:

1. Open netedit
1. Create new network
1. Select "Mode for delete elements." with the eraser symbol
1. Click anywhere in the drawing space

Also happens when you delete your last edge.

Version: NETEDIT v0_31_0-859-gf5a680F
Note: I've compile from sources on Ubuntu 14.04, HEAD at f5a680f0b08bf471e172e18a98b3a4d63c030e42

Thanks for the hard work!

**Comment by palvarezlopez** [comment]
Hi,

Thanks for the report. I'm going to check it.

Regards

**Comment by palvarezlopez** [comment]
@vtalpaert I have already fixed it in [8f2b825]
