### ISSUE TITLE
edge deletion bug in netedit

### ISSUE THREAD

**Issue by leoluecken** [DLR-TS/sumo#3627]
Edge is deleted when clicking somewhere else
To reproduce:
Select deletion mode ('d')
delete an edge
right click another (was the reverse one when I encountered the bug), select 'duplicate lane'
click anywhere on the background
then the edge with the duplicated lane is deleted.

**Comment by namdre** [comment]
I could easily reproduce this.

**Comment by palvarezlopez** [comment]
@leoluecken Thanks for the reporting.
