### ISSUE TITLE
invalid ride generated for car-public transfer

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3629]
In a scenario where the person should
- rides to an edge near the station
- walk to the trainStop
- ride the train
- walk to destination

a ride is generated that uses the car to arrive at the destination trainStop and then walk as if arrived by train.

**Comment by namdre** [comment]
see bugreports folder

**Comment by behrisch** [comment]
Seems to be a bug in the access generation when writing the ptstops file. There is an access connecting the last car edge to Hbf

**Comment by namdre** [comment]
The access edge was added manually and should have connected to the first train stop rather than the destination. My mistake then.
