### ISSUE TITLE
gui tests not finishing

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#3632]
when starting gui tests the GUI windows do not close so all tests time out

**Comment by palvarezlopez** [comment]
I'm working on it.

**Comment by palvarezlopez** [comment]
@behrisch I have tested all Netedit test in my Computer, and all test works. GUI tests use Control + Q to close Netedit. Can you check if the windows computer, in which Netedit test run, has a Keyboard?

**Comment by behrisch** [comment]
@palvarezlopez netedit is not affected, it is just a sumo-gui problem. The simulation just does not start.

**Comment by palvarezlopez** [comment]
@behrisch I cannot reproduce it. All of my Simulations usin SUMO GUI works as expected. After the simulation, I can close GUI-SUMO. Can you show me an example please?

**Comment by behrisch** [comment]
@leoluecken It was aa58daa
