### ISSUE TITLE
Build fails with no-GUI option

### ISSUE THREAD

**Issue by yurivict** [DLR-TS/sumo#3655]
Adding the option ```--without-fox-config``` causes the build to fail. It still tries to include fx.h.

**Comment by behrisch** [comment]
Seems to work here. Can you post the precise error message?

**Comment by yurivict** [comment]
```
--- MSParkingArea.o ---
In file included from MSParkingArea.cpp:38:
../../src/utils/foxtools/MFXMutex.h:37:10: fatal error: 'fx.h' file not found
#include <fx.h>
         ^~~~~~
```

**Comment by behrisch** [comment]
This has already been fixed in d12b650e.

**Comment by zpymyyn** [comment]
It's not fixed to me. I still counter this problem

**Comment by palvarezlopez** [comment]
@zpymyyn Do you have a Log with the error?

**Comment by zpymyyn** [comment]
Hi, unfortunately I didn't save the error. It could be sth. like following:

> FXSingleEventThread.cpp:63:36: error: invalid conversion from 

> 

Anyway i removed the "include fix.h"  and then it seems work
