### ISSUE TITLE
visualize custom edge geometry endpoints

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3716]
- should be in a distinct color from junctions and geometry points
- allow manipulating them with move / delete

most of the code for regular geometry points should be usuable. The only distinctions are:
- coloring
- inner vs full geometry: by default only geometry points of the inner geometry are shown (endpoints excluded), when setting geometry points the results are (currently) only applied to the inner geometry. Endpoints must be recognized and treated differently

**Comment by palvarezlopez** [comment]
We have two possibilities for moving EndPoints: Either only move the last point, or moving the entire  shape (see image). What do you think that it's better?

![endpoints](https://user-images.githubusercontent.com/8238561/34037150-f02ab3de-e187-11e7-9a82-40de66d09fd2.png)

**Comment by namdre** [comment]
Only the endpoint itself should move. The effaet should be exactly the same as setting a new value for the virtual edge attribute shapeStart or shapeEnd (i'm only talking about edges here)
