### ISSUE TITLE
sumo : Depends: gdal-abi-2-1-2 but it is not installable

### ISSUE THREAD

**Issue by brylie** [DLR-TS/sumo#3717]
When trying to install sumo on Ubuntu 17.10, I get the following error:

```
The following packages have unmet dependencies:
 sumo : Depends: gdal-abi-2-1-2 but it is not installable
```

A search for the *gdal-abi-2-1-2* library points towards [libgdal20](https://packages.ubuntu.com/zesty/gdal-abi-2-1-2). On my system, however, *libgdal20* is already installed:

```
libgdal20 is already the newest version (2.2.1+dfsg-2build3).
```

**Comment by behrisch** [comment]
Can you try whether something like this solution works?
https://gis.stackexchange.com/questions/216780/cannot-install-qgis-2-18-from-repository-on-debian-stretch-package-gdal-abi-2/216898

**Comment by brylie** [comment]
Jep, that worked:

1. `sudo apt-get install equivs`

2. Create a text file (gdal_abi.txt) with the following text: 
```
    Section: misc
    Priority: optional
    Standards-Version: 3.9.2
    
    Package: gdal-abi-2-1-0
    Version: 2.1.0
    Depends: libgdal20
    Description: fake package for qgis which needs a gdal-abi-2-1-0
```
  
3. `sudo equivs-build gdal_abi.txt`
4. `sudo dpkg -i gdal_abi.txt`

**Comment by behrisch** [comment]
probably needs a fix at debian/ubuntu packaging but not here

**Comment by brylie** [comment]
@behrisch is there an upstream request with the Ubuntu packagers? Please help ensure this does not slip through the cracks.

**Comment by behrisch** [comment]
I am not a regular ubuntu user and would probably not be able to provide the info needed. Could you just do that, probably here: https://bugs.launchpad.net/? Thank You!

**Comment by brylie** [comment]
Who, on the SUMO team, is responsible for Linux packaging?

**Comment by brylie** [comment]
On Launchpad, there are two people listed as maintainers of the SUMO PPA:

- Anton Gladky
- Michael Behrisch

I believe I have raised this issue correctly, and respectfully ask that it be re-opened until resolved by the package maintainers.

**Comment by behrisch** [comment]
Thank you, I reopen until we get feedback from Launchpad.

**Comment by gladk** [comment]
Please do not use the workaround listed here. It just fakes the system!

I am not able to reproduce the problem neither with official Ubuntu version (0.30) nor with PPA (0.32).  I used the clean Ubuntu environment.

**Comment by brylie** [comment]
@gladk thanks for your reply. 

The SUMO Ubuntu package relies on a version of GDAL that is slightly outdated (2.1.2 released 27-Oct-2016). This conflicts with my geospatial toolkit (QGIS, etc.) which depends on a most recent version of GDAL (2.2.1 released 30-Jun-2017) [1][2].

- [1] https://qgis.org/debian/dists/artful/main/binary-amd64/Packages
- [2] https://qgis.org/debian-nightly/dists/artful/main/binary-amd64/Packages

Would it be possible to package SUMO so that it can be used with versions of GDAL newer than 2.1.2? E.g. any version in the 2.x series?

**Comment by gladk** [comment]
No. Sumo depends on the libgdal-dev [1], which means that the package depends on default gdal-version installed in system. If you install third-party software which does not rely on system libraries, than those packages need to be fixed. Not the original one.

[1] https://salsa.debian.org/science-team/sumo/blob/master/debian/control#L14

**Comment by brylie** [comment]
Hm, OK. On my system, libgdal-dev is installed:

```
dpkg -s libgdal-dev      
Package: libgdal-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 38039
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: gdal
Version: 2.2.1+dfsg-2build3
```

The only mention of `libgdal-dev` in the QGIS packaging is:

```
libgdal-dev (>= 1.10.1-0~)
```

How can I determine which SUMO dependency is linking to `gdal-abi-2-1-2`? I.e. I don't even have a package named `gdal-abi-*` available to install on my system:

The Debian `libgdal20` package seems to provide `gdal-abi-2-1-2`:
https://packages.debian.org/stretch/gdal-abi-2-1-2
https://packages.ubuntu.com/search?keywords=gdal-abi&searchon=names

Also, @gladk have you tried installing SUMO on Ubuntu (e.g. 17.10)?

**Comment by gladk** [comment]
Sumo in 17.10 depends on gdal-abi-2-2-1 [1] which is provided in the system. In your system sumo wants another package. Try to remove 3-rd party repos.

[1] https://packages.ubuntu.com/artful/sumo

**Comment by brylie** [comment]
OK, thanks for clarifying. It is just really confusing, because QGIS is the only other repo I have added that uses GDAL, and it relies on the same gdal-abi-2-2-1:

https://qgis.org/debian/dists/artful/main/binary-amd64/Packages

Anyway, I guess we can close this now, since there is not a clear solution.

**Comment by rupeshmeher4u** [comment]
The following packages have unmet dependencies:
 mysql-workbench : Depends: gdal-abi-2-1-2
                   Depends: libmariadbclient18 (>= 10.0.14) but it is not going to be installed
                   Recommends: ttf-bitstream-vera but it is not going to be installed
                   Recommends: mysql-utilities but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

i have this issue in debian 10 can someone fix it

**Comment by behrisch** [comment]
@rupeshmeher4u Here are not so many people reading this. You might want to consider asking on the mailing list, see https://sumo.dlr.de/docs/Contact.html

**Comment by spicysardine** [comment]
> Jep, that worked:
> 
>     1. `sudo apt-get install equivs`
> 
>     2. Create a text file (gdal_abi.txt) with the following text:
> 
> 
> ```
> Section: misc
> Priority: optional
> Standards-Version: 3.9.2
>     
> Package: gdal-abi-2-1-2
> Version: 2.1.2
> Depends: libgdal20
> Description: fake package for qgis which needs a gdal-abi-2-1-2
> ```
> 
>     1. `sudo equivs-build gdal_abi.txt`
> 
>     2. `sudo dpkg -i gdal_abi.txt`

Thanks for the solution. You probably  meant to install the resulting deb. dpkg -i cannot install text files

**Comment by lcipolina** [comment]
> osgearth development package

Indeed, this was exactly my case. After I've downloaded those libraries, my entire SUMO disappeared and I could re-install it with apt-get.

The only option was to build it again from source. Like this:
https://sumo.dlr.de/docs/Installing/Linux_Build.html

**Comment by edgaremanu** [comment]
> > osgearth development package
> 
> Indeed, this was exactly my case. After I've downloaded those libraries, my entire SUMO disappeared and I could re-install it with apt-get.
> 
> The only option was to build it again from source. Like this:
> https://sumo.dlr.de/docs/Installing/Linux_Build.html

Please help me. I have this error:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sumo : Depends: gdal-abi-2-2-3
E: Unable to correct problems, you have held broken packages.

**Comment by edgaremanu** [comment]
> When trying to install sumo on Ubuntu 17.10, I get the following error:
> 
> ```
> The following packages have unmet dependencies:
>  sumo : Depends: gdal-abi-2-1-2 but it is not installable
> ```
> 
> A search for the _gdal-abi-2-1-2_ library points towards [libgdal20](https://packages.ubuntu.com/zesty/gdal-abi-2-1-2). On my system, however, _libgdal20_ is already installed:
> 
> ```
> libgdal20 is already the newest version (2.2.1+dfsg-2build3).
> ```
Please help me. I have the next error:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sumo : Depends: gdal-abi-2-2-3
E: Unable to correct problems, you have held broken packages.
