### ISSUE TITLE
improve visualization and editing of bidirectional rails (superposed edges)

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3720]
- add virtual boolean attribute (bidiRail) computed as in microsim based on geometry
- add visualization option for drawing: draw rail edges at half width and with a small offset to the right as if they had lanespread right so that both directions are visible at the same time (also for connections)

**Comment by palvarezlopez** [comment]
Should this options be implemented in **GNECreateEdge** Frame? (#2431)

**Comment by namdre** [comment]
I think no create-edge option is needed as it is sufficient to activate the 'Two-way' checkbox and set spread type to 'center'.
