### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by iamxg** [DLR-TS/sumo#3732]
Hi,
I installed sumo on my computer according to steps introduced in "http://sumo.dlr.de/wiki/Installing/Linux_Build". But there is the following problem. Please help me!
 
![image](https://user-images.githubusercontent.com/30093996/34135699-e3c82034-e427-11e7-8e26-32e0938f429f.png)

**Comment by behrisch** [comment]
Environment variables do not "survive" sudo. 

It is not necessary to sudo when running sumo or any of the scripts, so you could just do `python osmWebWizard.py`. But if you insist, see here https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo

**Comment by iamxg** [comment]
Thanks a lot!
