### ISSUE TITLE
GUI Tests dont't work correctly in Full HD Resolution

### ISSUE THREAD

**Issue by palvarezlopez** [DLR-TS/sumo#3746]
In Full HD Resolution (1920x1080) clicks over nets aren't precise, and generates nets with differents coordinates. Using Grid in all test can be a solution.

**Comment by palvarezlopez** [comment]
![sin titulo](https://user-images.githubusercontent.com/8238561/35557687-1dc9c6bc-05a6-11e8-87d4-755534a3075d.png)

Problem is caused by Scaling, not by resolution

**Comment by sumotest** [comment]
It seems to be impossible to change scaling on the server from the outside https://social.technet.microsoft.com/Forums/de-DE/2eccf23b-badc-4f51-9e37-e61b064072ea/change-dpi-scaling-inside-rdp-session-2008-r2-2012-r2?forum=winserverTS.
My client has 100%, so it is not clear how to proceed
