### ISSUE TITLE
replace tripinfo-output attribute waitSteps by waitingTime (in s)

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3749]
waitingTime and waitSteps are identical with default step-length of 1s  
but waitingTime in seconds is deemed more useful than the number of simulation steps for subsecond simulation.

**Comment by dominique-AR** [comment]
Hi namdre,

Thanks for the great job you've done first of all. I've using Sumo simulation tools for few weeks now. After generating some trip output file we are facing an column error in aggregating data with GenStats. Can you help us please?
 First, You told above that Waitsteps and Waiting Time means the same things. So can we juste replace "waitingTime" column with "Waitsteps"? 
Secondly, we find a "waitingcount" Column. Did this column having something in common with "Waitsteps" or not?*

Kind regards,

**Comment by namdre** [comment]
- by default, one simulation step is one second. In this case waitSteps has the same value oas waitingTime
- if you set an option **--step-length 0.5** then the simulation runs with a higher time-resolution and waitSteps will be twice the number of waitingSeconds
- waitingCount is the number of distinct waiting episodes (the vehicle was driving in between waiting)

**Comment by dominique-AR** [comment]
It's pretty clear, Thank you very much @namdre.
