### ISSUE TITLE
update Xerces to 3.2.0

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#3750]
on Linux it already runs fine, Windows build is still using the self patched version

**Comment by behrisch** [comment]
test server updated, wiki adapted, new version released at sourceforge

**Comment by palvarezlopez** [comment]
@behrisch I think that currently there are many users that are using the Xerces 3.1. Should we add a Warning message during compilation to inform that Xerces 3.1 is deprecated in SUMO?

**Comment by behrisch** [comment]
No the chinese streets are a rather rare usecase and everything else works fine (at least the linux users are not complaining and most of them probably use 3.1.x with the same bug as well).
