### ISSUE TITLE
`traci.edge.getLaneNumber` not implemented

### ISSUE THREAD

**Issue by c433li** [DLR-TS/sumo#3759]
Method `traci.edge.getLaneNumber` exists in the documentation page: http://www.sumo.dlr.de/daily/pydoc/traci._edge.html#EdgeDomain-getLaneNumber , but it's actually not implemented.

**Comment by namdre** [comment]
see http://sumo.dlr.de/wiki/FAQ#Why_does_SUMO_not_behave_as_documented_in_this_wiki.3F
