### ISSUE TITLE
TraCI python client, vehicles in GUI show empty body

### ISSUE THREAD

**Issue by chrisshen** [DLR-TS/sumo#3763]
I'm using TraCI python client to run and control SUMO. 

SUMO version is SUMO-0.32.0

When I use traci API to add vehicles and set color of vehicles, the added vehicles show empty body.

The python code is as follows:
```python
traci.vehicle.add('v-%i' % (step+1), rou, (step+1), 0, 0, 0, "CarA")
traci.vehicle.setColor('v-%i' % (step+1), (0, 255, 255, 0))
```
Here the empty body means I can only show the vehicle ID, but can not see the vehicle in SUMO-GUI. The vehicles are actually there, but did not show.

If I remove `setColor() ` API, the added vehicles show normal body.

I guess `setColor()` API has some compatible issue with GUI. 

I attach the screenshot here.
![test](https://user-images.githubusercontent.com/4958558/34762833-8e881fae-f62c-11e7-8ef0-f263c808ec26.png)

**Comment by behrisch** [comment]
Please note that the color value is RGBA, where the  last component (alpha) defines transparency in the 0-255 range where 0 means fully transparent. So the behavior is correct but you probably want the last component to be 255. This was wrong in the docstring.

**Comment by chrisshen** [comment]
Ah....Thanks!
