### ISSUE TITLE
sumopy_gui.py error

### ISSUE THREAD

**Issue by iamxg** [DLR-TS/sumo#3764]
Hi,
I face the following error when I run sumopy_gui.py. I have intalled numpy. Does this mean that I must install OpenGL? My OS is ubuntu 16.04.
![image](https://user-images.githubusercontent.com/30093996/34778815-081514b0-f5e4-11e7-84e3-bd42191748c4.png)

**Comment by behrisch** [comment]
please try without sudo

**Comment by iamxg** [comment]
Error is the same as that I use sudo or don't use sudo.

**Comment by behrisch** [comment]
Please see here for SUMOPy installation instructions http://sumo.dlr.de/wiki/Contributed/SUMOPy#Linux

**Comment by behrisch** [comment]
Please reopen if the problem persists
