### ISSUE TITLE
Lanes lack of getIncoming() API for TraCI in lane.py, sumolib

### ISSUE THREAD

**Issue by chrisshen** [DLR-TS/sumo#3772]
I am using python code to run SUMO-0.32.0. 

I need to access **incoming** connections of a lane, but surprisingly only **getOutgoing()** API exists in lane.py of tools/sumolib. 

Is this some special consideration?

If not, suggest to add **getIncoming()** API in lane.py of tools/sumolib.

**Comment by leoluecken** [comment]
Closed via  e253e19
