### ISSUE TITLE
osmWebWizard.py +sumopy-GUI 

### ISSUE THREAD

**Issue by iamxg** [DLR-TS/sumo#3777]
Hi all,
I selected a small area to generate a road network file by using osmWebWizard.py. But this road network file can't import in sumopy-GUI. Always occurs the following errors and then quits. Could you let me know why and how to resolve this problem.
Best Regards,
Xian
![image](https://user-images.githubusercontent.com/30093996/35232988-8967d3e0-ff62-11e7-9528-15faf15c660d.png)

**Comment by behrisch** [comment]
Small test networks work here. Can you give the network or at least the coordinates and the sumo version?

**Comment by iamxg** [comment]
Hi,
Thank you very much for your replying. My sumo version is 0.25. I selected area as follows.
![image](https://user-images.githubusercontent.com/30093996/35286965-f55d5a38-0026-11e8-80d9-8d76b3135073.png)
Xian Guo

**Comment by behrisch** [comment]
Version 0.25 did not contain SUMOPy. Can you use the most recent version?

**Comment by iamxg** [comment]
Hi,
Thank you for your replying.
I install these tools according to the following materials:
http://sumo.dlr.de/wiki/Installing
https://github.com/DLR-TS/sumo
Could you tell me how to install the latest version?
Best Regards,
Xian Guo

**Comment by iamxg** [comment]
Hi behrisch,
I find version 0.32. I will try it. Thanks a lot!
Best Regards,
Xian Guo

**Comment by iamxg** [comment]
Hi behrisch,
This problem has been solved. Thank you very much!
Best Regards,
Xian Guo
