### ISSUE TITLE
Fedora - Updated Build?

### ISSUE THREAD

**Issue by cipherboy** [DLR-TS/sumo#3789]
Hello,

We are running SUMO and were hoping to install on Fedora 27, however the official [site](http://www.sumo.dlr.de/userdoc/Installing.html) points to a set of [repositories](http://download.opensuse.org/repositories/home:/behrisch/) that contain only a Fedora 25 package. This package doesn't install on F27 as numerous version conflicts occur. 

If we take the time to build/update the Fedora rpmspec, are you interested in maintain this as part of the officially built packages?

Thanks,
Alex

**Comment by behrisch** [comment]
Hi,
thank you for offering that but I would like to keep all in one spec if possible. I tried adding Fedora 27 to
https://build.opensuse.org/project/show/home:behrisch
Please check whether the result suits your needs (may take some time until the build is finished).

Best regards,
Michael

**Comment by cipherboy** [comment]
Ah, many thanks! That appears to install a lot better. :)

-- Alex
