### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DanielLSM** [DLR-TS/sumo#3790]
Im getting a build error with the current repo: BinaryFormatter.cpp:31:21: fatal error: version.h: No such file or directory compilation terminated.

How can I solve it?

**Comment by palvarezlopez** [comment]
Hello,

What compiler are you using?

Regards

Von: Daniel Marta [mailto:notifications@github.com]
Gesendet: Mittwoch, 31. Januar 2018 13:02
An: DLR-TS/sumo
Cc: Subscribed
Betreff: [DLR-TS/sumo] Build error (#3790)


Im getting a build error with the current repo: BinaryFormatter.cpp:31:21: fatal error: version.h: No such file or directory compilation terminated.

How can I solve it?

**Comment by DanielLSM** [comment]
Hello @palvarezlopez I solved it using a ./configure flag, but now I run into another issue. sumo-gui was not built, how can I solve this?

**Comment by palvarezlopez** [comment]
Hello,

Are you sure that you have installed FOX-Devel libraries?

Von: Daniel Marta [mailto:notifications@github.com]
Gesendet: Mittwoch, 31. Januar 2018 15:35
An: DLR-TS/sumo
Cc: Alvarez Lopez, Pablo; Mention
Betreff: Re: [DLR-TS/sumo] Build error (#3790)


Hello @palvarezlopez<https://github.com/palvarezlopez> I solved it using a ./configure flag, but now I run into another issue. sumo-gui was not built, how can I solve this?

**Comment by DanielLSM** [comment]
My bad, did not read fully the pre-installation.
