### ISSUE TITLE
Vehicle Simulation

### ISSUE THREAD

**Issue by iamxg** [DLR-TS/sumo#3792]
Hi,
I'd like to extract an area that specified size from a map. For example, an area with 1500m*1500m. But I don't know how to extract. Could you help me?

Best Regards,
Xian

**Comment by leoluecken** [comment]
Take a look at the WebWizard:
http://sumo.dlr.de/wiki/Tutorials/OSMWebWizard
Best,
Leo


Von: Xian Guo [mailto:notifications@github.com]
Gesendet: Mittwoch, 31. Januar 2018 18:40
An: DLR-TS/sumo
Cc: Subscribed
Betreff: [DLR-TS/sumo] Vehicle Simulation (#3792)


Hi,
I'd like to extract an area that specified size from a map. For example, an area with 1500m*1500m. But I don't know how to extract. Could you help me?

Best Regards,
Xian

**Comment by iamxg** [comment]
Thanks a lot！


Xian G




-----Original Message-----
