### ISSUE TITLE
Traci find route bug

### ISSUE THREAD

**Issue by XavierLavenir** [DLR-TS/sumo#3793]
Hi,

I think I have a found a bug in the traci.simulation.findRoute function. I have called this function for vtype="DEFAULT_PEDTYPE" to state the the routing is for a pedestrian. However, it seems to return a route for a vehicle. 

This is because the to and from edges I am routing are directly connected for pedestrians but a vehicle would have to make a large detour since there are one way streets.

**Comment by behrisch** [comment]
This is by design. The findRoute function is for vehicles and just setting a different vtype won't change the behavior. Please use findIntermodalRoute for persons. I updated the documentation http://sumo.dlr.de/wiki/TraCI/Simulation_Value_Retrieval#Command_0x86:_Find_Route.
