### ISSUE TITLE
Interface with SUMO

### ISSUE THREAD

**Issue by DanielLSM** [DLR-TS/sumo#3795]
Is it possible to interface SUMO in such a way that you can send commands (velocities, accelarations, positions) at each time step? If not, is there any part of the code i should look to make a socket-based interface to control each step?

Thank you.

**Comment by behrisch** [comment]
You may want to look at [TraCI](http://sumo.dlr.de/wiki/TraCI) especially at the [MoveToXY command](http://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#move_to_XY_.280xb4.29). There are already clients for Python, Java, C++ and Matlab. Please try to rather use the mailing list for questions, see http://sumo.dlr.de/wiki/Contact
