### ISSUE TITLE
TraCI API: getLoadedNumber() returns always 0 in _simulation.py

### ISSUE THREAD

**Issue by chrisshen** [DLR-TS/sumo#3800]
When I use this TraCI API, getLoadedNumber(), it always returns 0, though the simulation loads hundreds vehicles at each step. It is in _simulation.py of TraCI tools.

The simulation status is shown in this screenshot:
![image](https://user-images.githubusercontent.com/4958558/35843457-a47d5fc0-0b4b-11e8-804f-812985b8fd75.png)

The print results are getLoadedNumber() and getLoadedIDList()
```python
print(traci.simulation.getLoadedNumber(), traci.simulation.getLoadedIDList())
```
![image](https://user-images.githubusercontent.com/4958558/35843493-dc6f9b78-0b4b-11e8-95a4-546b10233867.png)

**Comment by leoluecken** [comment]
In the tests, getLoaded() succeeds. I'll close this for now.
Please recheck, if traci.simulation.getLoaded() is what you are looking for. If you want to determine the number of vehicles, which are inserted into the road network in the current step, take a look at traci.simulation.getDepartedIDList() or traci.simulation.getDepartedNumber().
If this does not solve your issue and you really do have getLoadedNumber()==0 for *all* time steps, please reopen the issue.
