### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by ab2229** [DLR-TS/sumo#3836]
I am currently attempting to compile SUMO on Windows using Microsoft Visual Studio 2017 with CMake. I have followed the manually generated tutorial given on the [Wiki](http://sumo.dlr.de/wiki/Installing/Windows_CMake), as the automatic generation did not produce any output.

I have pulled the most recent [libraries](https://github.com/palvarezlopez/SUMOLibraries) and ensured they are all in my path. 

Unfortunatly, each time I attempt to compile the project I am given the error message:

MSB6006 "cmd.exe" exited with code 9009. Project - gl2ps. File - Microsoft.CppCommon.targets. Line - 171

I would be very grateful if anyone would be able to assist me with this problem.

Thank you,

Aaron

**Comment by behrisch** [comment]
Do you have git installed and is it in your path?

**Comment by ab2229** [comment]
Yes, I do

**Comment by seb-ehm** [comment]
@ab2229 I just added a commit that should fix your issue.
