### ISSUE TITLE
simulations with trips and much depart delay suffer slowdown from frequent rerouting

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3865]
the default value of --device.rerouting.pre-period is 1  which causes undeparted vehicles to trigger routing every second.
This is probably not needed and the default value should be raised.

**Comment by namdre** [comment]
@behrisch I would change the default to 60s. Any objections?

**Comment by behrisch** [comment]
60s is OK, should we change the adaptation interval default as well?
Does the scenario have many different depart edges or why isn't this covered by "sloppy insert"?

**Comment by namdre** [comment]
on average every 5th pre-insertion rerouting call is skipped.
