### ISSUE TITLE
osmWebWizard broken

### ISSUE THREAD

**Issue by shapewerk** [DLR-TS/sumo#3873]
Under Windows10-64bit with a fresh install of Sumo32 and Python 2.7 the osmWebWizard does not generate default scenario (of Berlin). No error nor other message is displayed in the Python console, Sumo-GUI is not started.

Same behaviour having Firefox, Chrome or Edge set as Webbrowser. No Javascript errors either.
Please let me know what I do wrong?

**Comment by namdre** [comment]
what happens when you run "python osmWebWizard.py" on the command line from within the sumo/tools folder?

**Comment by shapewerk** [comment]
No difference, Web browser and terminal remain unchanged for hours. Should I see any progress bar|messages? Where are the results written to?

**Comment by namdre** [comment]
Until you click the appropriate controls in the web browser, nothing is generated. Once you do, outputs are written to a sub folder of the working directory (wherever you called the script from or to the user documents directory).

What kind of strack trace do you seen when aborting the script with ctrl+c ?

**Comment by shapewerk** [comment]
Sure, in the web browser I use default settings and hit "Generate Scenario" button. I tried to select a tiny area as well, still no results in the working directory or progress on screen. Can you actually verify that osmWebWizard works in SUMO32(64bit) and f.i. Firefox59(64bit)?
When aborting osmWebwizard.py 5 minutes after clicking "Generate Scenario" , I get KeyboardInterrupt in line 629 (server.serveforever())

**Comment by behrisch** [comment]
Works here with Firefox 58.0.2 (64bit). Firefox 59 is still beta? Any firewalls active?

**Comment by namdre** [comment]
I can confirm it is workign on for windows 7.

**Comment by shapewerk** [comment]
Thank you for the confirmation. I turned off windows firewall, antivirus - used Edge, Chrome, FF - still not working. My Windows 10 Pro version is 1709, build 16299.248. Python version 2.7

**Comment by palvarezlopez** [comment]
I check it in my Windows 10 Pro N using Chrome, and work it. Do you have some server/application like XAMMP or similar running in background?

**Comment by shapewerk** [comment]
Thanks to you all I could finally locate the problem. After uninstalling python 2.7.0 and applying the latest 2.7.14 (64bit) the generation worked like a charm :-) No problem with the SUMO release, just a heads up to use python 2.7.14.
