### ISSUE TITLE
keepClear not setable in Netedit

### ISSUE THREAD

**Issue by ZoltanBaksa** [DLR-TS/sumo#3878]
Hi,

I have created a network, where I turned the keepClear to false with netconvert (with --default.junctions.keep-clear false), so all connection definition contains keepClear="0"
First Issue:
When I load the network into Netedit, I see at inspection mode by the junctions that the keepClear is set to true. If I save the network, nothing changes in the net xml file.
Second Issue:
If I set the flag to "false", and then back to "true", nothing changes in the net xml file.
If I save the file with "Save as" nothing is changed.
Third Issue:
I do not see the keepClear setting at the connections in inspection mode.
I have used the 0.32 released version and also the latest development version (08.03.2018)
Please check

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Hi, thanks for the report, I check it.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I have fixed the problem. On the other hand there is a crash during manipulating connections that are being fixed in #3779
