### ISSUE TITLE
cannot edit picture parameters in netedit decals

### ISSUE THREAD

**Issue by ZoltanBaksa** [DLR-TS/sumo#3884]
Hi,
I use high resolution pictures as background in netedit to position precisely the street elements (traffic lights, junctions...) but in development version (v0_32_0+0673-f3c59ea9bc) I'm not able to edit the parameters of the loaded picture (position, size, etc.) in the view settings window at background page
In the latest release version 0.32 this was not a problem.
Please check it

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks for report it. I'm going to check it.

**Comment by namdre** [comment]
I broke this in [1361dd626e]
