### ISSUE TITLE
Cannot edit TLS ID

### ISSUE THREAD

**Issue by ZoltanBaksa** [DLR-TS/sumo#3885]
Hi,
In development version (v0_32_0+0673-f3c59ea9bc) I'm not able to create TLS join with editing the ID of each participant TLS. When I switch to another junction the original value is set again. In 0.32 version this was not an issue.
Please check

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks for report it. Currently we're improving the TLSEditorFrame, and some functions are disabled. I'll report you when  TLSEditorFrame is finished

**Comment by namdre** [comment]
@palvarezlopez : This has nothing to do with the tlseditorframe because the id is edited in inspect mode for the junction.
@ZoltanBaksa  It is working for me in 32+696. Can you give steps for reproducing this?

**Comment by ZoltanBaksa** [comment]
Hi,
I tried it in traffic light mode not in inspect mode, with inspect mode it works.
Sorry for the wrong report.
