### ISSUE TITLE
Inaccurate map output from netconvert tool

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3894]
When using netconvert to convert from an osm map, the traffic signal systems in multi road intersections seem incorrect. The example below can illustrate the issue:

![trafficlights_issue](https://user-images.githubusercontent.com/37397574/37452059-75f24b3a-286e-11e8-866f-b113e0247a26.png)

![osm_map](https://user-images.githubusercontent.com/37397574/37452029-607e569a-286e-11e8-84b9-892580269b77.png)

https://www.google.com.sg/maps/@1.2993241,103.7854482,248m/data=!3m1!1e3

The 4 sets of traffic signal system should have been merged into one single system that manages the whole intersection, rather than 4 separate systems.

The osm file in question is:
[one-north_osm.osm.zip](https://github.com/DLR-TS/sumo/files/1814470/one-north_osm.osm.zip)

and the command used to generate the map is:
`netconvert --osm-files one-north_osm.osm -o map.net.xml --geometry.remove --roundabouts.guess --tls.join --tls.guess-signals`

Am I missing some flags that could allow me to obtain a better, SUMO network conversion, or is this already a known issue?
I am happy to clarify and provide more details if needed.

Thanks!

**Comment by namdre** [comment]
Hello,
you are missing the option --junctions.join
See http://sumo.dlr.de/wiki/Networks/Import/OpenStreetMap#Junctions
regards,
Jakob

2018-03-15 9:22 GMT+01:00 sumo-fanclub <notifications@github.com>:

**Comment by sumo-fanclub** [comment]
Thanks for the reply,

I tried the command but i received this warning:

`Warning: Not joining junctions 1119642655,1795305236,1795305239,1795305244,1795305254,1795305256,1807069528,1807069529,1807069530,1807069531,239612802,4732376962 because the cluster is too complex (5 incoming edges)`.

There should only be 4 incoming edges in the osm file.

**Comment by namdre** [comment]
most likely one of the pedestrian paths got merged into the cluster and thus increases the number of incoming edges
