### ISSUE TITLE
netconvert.exe has stopped working

### ISSUE THREAD

**Issue by rbsumo** [DLR-TS/sumo#3898]
When trying to convert a network from visum to sumo I get several warning messages like:

```
Warning: Edge's '2100026319' from- and to-node are at the same position.
Warning: Edge's '-2100026319' from- and to-node are at the same position.
```
and
```
Warning: Incoming connector '900018-436041' will not be build - would be not connected to network.
Warning: Outgoing connector '900018-438146' will not be build - would be not connected to network.
```

After the warnings about connectors netconvert crashes and no sumo file is created. 

![grafik](https://user-images.githubusercontent.com/37401137/37456856-aaba81a8-2840-11e8-9388-d896e86c824e.png)

The log which is created by
`--log filename`
ends with the the connector warnings.

Is there a way to see (log) why netconvert is crashing? Is it due to the Warnings or because netconvert starts converting the "Fahrstreifen" (lanes)? 

For conversion I'm using:
`netconvert --visum file.net --log file.log`

**Comment by namdre** [comment]
Please provide test input so we can reproduce this. If you cannot attach a sample publicly, send it directly to namdre.sumo@dlr.de. 
Note, that we haven't used Visum import in a while so there might be issues with the format version.

**Comment by namdre** [comment]
Note, that the given email adress was wrong and is now corrected.

**Comment by namdre** [comment]
Lots more visum import fixes in recent commits. Should be working now.
