### ISSUE TITLE
Road agents follow unnatural paths in traffic junctions

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3899]
When using netconvert to convert a junction from an OSM file, the following network with unnatural paths is generated:
![sumo_osm](https://user-images.githubusercontent.com/37397574/37502091-2e94ed76-290c-11e8-8b27-2329a1b9c2fa.png)

Building an artificially parallel junction with the netedit tool gives slightly improved results, but still incorrect.
![sumo_junction_1](https://user-images.githubusercontent.com/37397574/37502010-cef82220-290b-11e8-814b-5f70b1c48f90.png)

Is this already a known issue?

Thanks!

**Comment by namdre** [comment]
Hello,
this looks as if you try to build a network for a lefthand-drive country.
Please add the option --lefthand and report if the problem is fixed.

**Comment by sumo-fanclub** [comment]
Hi,
Yes, I have tried the option and the issue is fixed in sumo-gui. I am able to get a good simulation.

However Netedit crashes when I try to open the road network.
This is the sumo network file:
[map-lefthand.net.xml.zip](https://github.com/DLR-TS/sumo/files/1818238/map-lefthand.net.xml.zip)

Thank you so much for fixing my issues!

**Comment by namdre** [comment]
Unfortunately, we rarely work with lefthand networks so you are the first to notice that editing lefthand networks was broken in version 0.32.0. (https://github.com/DLR-TS/sumo/issues/3900)
Please upgrade to the latest development version where this issue has just now been fixed.

You can either build from the github sources or download the freshly compiled windows binaries  **tomorrow** at http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version
