### ISSUE TITLE
Click event in inspection mode in Netedit not appropiate

### ISSUE THREAD

**Issue by ZoltanBaksa** [DLR-TS/sumo#3903]
Hi,
I use the 0_32_0+0706-708d1aa54e version of SUMO.
If I set the "show connections" checkbox in inspection mode, not the properties of the object below mouse arrow is showed, when I'm clicking on the map. Usually on a wide area one connection's property is shown, even if there are more connections, junctions or edges under the mouse arrow. If I remove the selection of "Show connections", the click event is handled correctly.
The fault was not present in 0.32 version.

**Comment by namdre** [comment]
I am unable to reproduce this. Please send me a small example network and specify the click coordinate which produces wrong behavior.

**Comment by ZoltanBaksa** [comment]
I have sent you an example via email, because if I cut the problematic part, the effect does not occure again.

**Comment by namdre** [comment]
Thanks for reporting. It was caused by improper handling of somewhat unusual geometry.
