### ISSUE TITLE
keepClear lost at reload of network in Netedit

### ISSUE THREAD

**Issue by ZoltanBaksa** [DLR-TS/sumo#3904]
Hi,
I have created a network with Netedit, where I have set the keepClear to false. After I closed the network, I have created a backup. After I reloaded the original and did some other changes, the previous keepclear settings were lost, I had to redo all again.
I use the 0_32_0+0706-708d1aa54e version.
Please check it

**Comment by namdre** [comment]
thank you for reporting this regression.
