### ISSUE TITLE
A second manual CMake run is required after compilation of GL2PS on Windows

### ISSUE THREAD

**Issue by seb-ehm** [DLR-TS/sumo#3911]
Currently, if Sumo is compiled on Windows and gl2ps is not preinstalled, a single CMake configure/generate and compile cycle is not sufficient to correctly include gl2ps.

gl2ps is included in Sumo on Windows using `ExternalProject_Add` in the main CMakeLists.txt, if it isn't found by `find_package(GL2PS)`. This means, that gl2ps is downloaded an built at compile time. This in turn means, that the command `FIND_LIBRARY(GL2PS_LIBRARY ... ` always fails in the initial CMake configure step, as the library is not yet available. Therefore, `HAVE_GL2PS` is not set and the library `z_utils_gui_window` is compiled without gl2ps support.
Only when CMake is rerun manually after a successful initial build, `FIND_LIBRARY(GL2PS ...` succeeds. If Sumo is compiled again, `z_utils_gui_window` is compiled with gl2ps support.

A possible workaround would be to add a custom command to the `gl2ps` target, right after `ExternalProject_Add(...)`, like so:
    
    add_custom_command(TARGET gl2ps POST_BUILD COMMAND ${CMAKE_COMMAND} ${CMAKE_BINARY_DIR}) 
    
This would cause a CMake rerun after the compilation of gl2ps. Here, CMake is going to correctly discover `gl2ps.dll` and modify the Visual Studio Solution, which causes Visual Studio to suggest reloading all projects. This in turn gives a strong hint to the person compiling Sumo that a second compilation run is necessary.

But I'm not quite sure if there isn't a better solution. In my opinion, a solution that avoids a second CMake run would be preferable; the next best solution would require a second CMake run, but only cause Visual Studio to reload one or two projects, and not the complete VS solution, to make it easier to identify the reason for the reload.

**Comment by behrisch** [comment]
Your proposal definitely improves the situation but my initial idea was to build something like the gtest thing where the library is already built at "configure" time, but I failed maybe due to my limited cmake understanding or maybe because the gl2ps build is not flexible enough to support. Could you have a look here?

**Comment by behrisch** [comment]
I tried again hopefully more luck this time. Could you have a look whether it works on your side?

**Comment by seb-ehm** [comment]
It works for me! The only small drawback might be that gl2ps is build in debug mode, so it might run a bit slower than in release, but that shouldn't be an issue.

**Comment by FlixFix** [comment]
> Currently, if Sumo is compiled on Windows and gl2ps is not preinstalled, a single CMake configure/generate and compile cycle is not sufficient to correctly include gl2ps.
> 
> gl2ps is included in Sumo on Windows using `ExternalProject_Add` in the main CMakeLists.txt, if it isn't found by `find_package(GL2PS)`. This means, that gl2ps is downloaded an built at compile time. This in turn means, that the command `FIND_LIBRARY(GL2PS_LIBRARY ... ` always fails in the initial CMake configure step, as the library is not yet available. Therefore, `HAVE_GL2PS` is not set and the library `z_utils_gui_window` is compiled without gl2ps support.
> Only when CMake is rerun manually after a successful initial build, `FIND_LIBRARY(GL2PS ...` succeeds. If Sumo is compiled again, `z_utils_gui_window` is compiled with gl2ps support.
> 
> A possible workaround would be to add a custom command to the `gl2ps` target, right after `ExternalProject_Add(...)`, like so:
> 
> ```
> add_custom_command(TARGET gl2ps POST_BUILD COMMAND ${CMAKE_COMMAND} ${CMAKE_BINARY_DIR}) 
> ```
> 
> This would cause a CMake rerun after the compilation of gl2ps. Here, CMake is going to correctly discover `gl2ps.dll` and modify the Visual Studio Solution, which causes Visual Studio to suggest reloading all projects. This in turn gives a strong hint to the person compiling Sumo that a second compilation run is necessary.
> 
> But I'm not quite sure if there isn't a better solution. In my opinion, a solution that avoids a second CMake run would be preferable; the next best solution would require a second CMake run, but only cause Visual Studio to reload one or two projects, and not the complete VS solution, to make it easier to identify the reason for the reload.

Thank you very much hinting for a double configuration. This made my day, after trying to get the Screenshot Option to work and link agains gl2ps the whole day!
