### ISSUE TITLE
Realistic lane changing behavior

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3918]
Hi, I am interested in using SUMO as a traffic simulator.

However, the teleportation of a vehicle during lane changing is not feasible for my needs.
I was wondering if there is a better method of lane changing that has been already implemented which allows for the vehicles to drive into their destination lanes gracefully.

I understand that a lot of effort has been put into this project and any help (even to point me to the relevant source files) is appreciated.

Thanks!

**Comment by namdre** [comment]
Two models for smooth lane changing already exist: http://sumo.dlr.de/wiki/Simulation/SublaneModel
