### ISSUE TITLE
Left-hand drive lane-changing issue

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3923]
When in lefthand drive mode, lane changing behavior does not seem correct. Are there some flags that I am missing for a left-hand drive system?

[lefthand_lanechange.zip](https://github.com/DLR-TS/sumo/files/1827775/lefthand_lanechange.zip)

**Comment by sumo-fanclub** [comment]
Hi @namdre,
In the video, the car in the center is sliding off towards the right instead of the left, where its destination lane is. Once it leaves the lane, it teleport to the destination lane from the wrong angle.
Thanks again for looking at my issue
[bug.zip](https://github.com/DLR-TS/sumo/files/1828709/bug.zip)

**Comment by namdre** [comment]
Thank you for the report
