### ISSUE TITLE
Support for opendrive v1.4

### ISSUE THREAD

**Issue by ziyi-chong** [DLR-TS/sumo#3940]
Hi,
Using netconverter with publicly available opendrive files from atlatec seems to give invalid results.
It seems that this is caused by netconvert not supporting the v1.4 opendrive format as this warning is obtained as output:
> Warning: Given openDrive file 'KA-Suedtangente-atlatec.xodr' uses version 1.4;
>  Version 1.2 is supported.

netconvert arguments:
`--opendrive-files KA-Suedtangente-atlatec.xodr -o map.net.xml --geometry.remove --roundabouts.guess --tls.join --tls.guess-signals --lefthand --junctions.join`

test opendrive file:
http://www.atlatec.de/downloads/odr_sample.zip

**Comment by namdre** [comment]
Thank you for reporting.
Some lane types were not imported because the importer was assuming wrong names.
Either upgrade to the latest development version (only 1 file needs to be updated) or import using the option
--opendrive.import-all-lanes
