### ISSUE TITLE
How to implement different VClasses extending current ones?

### ISSUE THREAD

**Issue by jimonreal** [DLR-TS/sumo#3942]
I am looking to extend some type of vehicles, like pedestrians, and create a new type with different attributes.
Is there any place in the wiki where I can find how is this done?

Best regards,

**Comment by namdre** [comment]
this should be asked at the sumo-user or sumo-devel mailing list. See http://sumo.dlr.de/wiki/Contact

If you need to change existing attributes, see http://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes#Vehicle_Types

if you need to define completely new attributes and models, this is more difficult. If you tell us what you want to achieve, we may be able to give a hint.

**Comment by jimonreal** [comment]
Thanks!, I want to be able to simulate different types of pedestrians, kids, adults, and elderly people, which have different pace speeds.
