### ISSUE TITLE
Stop/yield Lines

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3955]
Is there a way to define stop/yield lines on each incoming road for junctions in SUMO's road network format?
If yes, how do I define them in NetEdit?

![image](https://user-images.githubusercontent.com/37397574/38069234-d8b469b8-3347-11e8-874c-48fb61ceba3f.png)

**Comment by namdre** [comment]
please post this type of question at the mailing list.
see http://sumo.dlr.de/wiki/Simulation/Intersections#Waiting_before_the_Intersection
