### ISSUE TITLE
Junction issue with map projection

### ISSUE THREAD

**Issue by sumo-fanclub** [DLR-TS/sumo#3965]
Hi,
There is an issue with maps with projections, the simulated agents appear to teleport when they enter the starting point of the road junctions. Also, it seems that the queuing model is also off. 
This is the map projection with issue:
`<location netOffset="-365043.32,-143389.88" convBoundary="4.58,81.33,172.77,204.71" origBoundary="103.786960,1.297000,103.791861,1.300145" projParameter="+proj=utm +zone=48 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>`

**Comment by sumo-fanclub** [comment]
[bug.zip](https://github.com/DLR-TS/sumo/files/1874620/bug.zip)

**Comment by namdre** [comment]
This has nothing to do with projections. The network is built with the option --no-internal-links.
For an explanation of what that entails, see http://sumo.dlr.de/wiki/Simulation/Intersections#Internal_links
