### ISSUE TITLE
Error: Cannot open include file: 'version.h': No such file or directory

### ISSUE THREAD

**Issue by durraniu** [DLR-TS/sumo#3967]
I am getting the `Error: Cannot open include file: 'version.h': No such file or directory` when I try to build it.   Following is the complete output:  

`1>------ Build started: Project: y_libgui, Configuration: Release x64 ------
2>------ Build started: Project: y_libmicrosim, Configuration: Release x64 ------
3>------ Build started: Project: y_libnetimport, Configuration: Release x64 ------
4>------ Build started: Project: z_libutils_iodevices, Configuration: Release x64 ------
5>------ Build started: Project: netedit_dialogs, Configuration: Release x64 ------
6>------ Build started: Project: z_optional_libtraciserver, Configuration: Release x64 ------
7>------ Build started: Project: z_libgui_dialogs, Configuration: Release x64 ------
2>MSStateHandler.cpp
1>GUIApplicationWindow.cpp
2>c:\users\durraniu\desktop\sumo-master\sumo-master\src\microsim\msstatehandler.cpp(31): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
4>BinaryFormatter.cpp
1>c:\users\durraniu\desktop\sumo-master\sumo-master\src\gui\guiapplicationwindow.cpp(32): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
4>c:\users\durraniu\desktop\sumo-master\sumo-master\src\utils\iodevices\binaryformatter.cpp(31): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
5>GNEDialog_About.cpp
2>Done building project "y_libmicrosim.vcxproj" -- FAILED.
1>Done building project "y_libgui.vcxproj" -- FAILED.
5>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netedit\dialogs\gnedialog_about.cpp(29): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
6>TraCIServer.cpp
4>Done building project "z_libutils_iodevices.vcxproj" -- FAILED.
8>------ Build started: Project: jtrrouter, Configuration: Release x64 ------
9>------ Build started: Project: netgenerate, Configuration: Release x64 ------
10>------ Build started: Project: od2trips, Configuration: Release x64 ------
11>------ Build started: Project: duarouter, Configuration: Release x64 ------
3>NILoader.cpp
6>c:\users\durraniu\desktop\sumo-master\sumo-master\src\traci-server\traciserver.cpp(38): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
5>Done building project "netedit_dialogs.vcxproj" -- FAILED.
12>------ Build started: Project: dfrouter, Configuration: Release x64 ------
7>GUIDialog_AboutSUMO.cpp
6>Done building project "z_optional_libtraciserver.vcxproj" -- FAILED.
13>------ Build started: Project: sumo, Configuration: Release x64 ------
7>c:\users\durraniu\desktop\sumo-master\sumo-master\src\gui\dialogs\guidialog_aboutsumo.cpp(30): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
7>Done building project "z_libgui_dialogs.vcxproj" -- FAILED.
14>------ Build started: Project: sumo-gui, Configuration: Release x64 ------
10>od2trips_main.cpp
9>netgen_main.cpp
8>jtrrouter_main.cpp
10>c:\users\durraniu\desktop\sumo-master\sumo-master\src\od2trips_main.cpp(33): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
8>c:\users\durraniu\desktop\sumo-master\sumo-master\src\jtrrouter\jtrrouter_main.cpp(31): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
9>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netgen\netgen_main.cpp(32): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
10>Done building project "od2trips.vcxproj" -- FAILED.
15>------ Build started: Project: polyconvert, Configuration: Release x64 ------
11>duarouter_main.cpp
12>dfrouter_main.cpp
8>Done building project "jtrrouter.vcxproj" -- FAILED.
9>Done building project "netgenerate.vcxproj" -- FAILED.
16>------ Build started: Project: activitygen, Configuration: Release x64 ------
17>------ Build started: Project: marouter, Configuration: Release x64 ------
11>c:\users\durraniu\desktop\sumo-master\sumo-master\src\duarouter\duarouter_main.cpp(31): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
12>c:\users\durraniu\desktop\sumo-master\sumo-master\src\dfrouter\dfrouter_main.cpp(34): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
13>sumo_main.cpp
16>AGFrame.cpp
16>c:\users\durraniu\desktop\sumo-master\sumo-master\src\activitygen\agframe.cpp(34): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
13>c:\users\durraniu\desktop\sumo-master\sumo-master\src\sumo_main.cpp(33): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
17>marouter_main.cpp
16>activitygen_main.cpp
16>c:\users\durraniu\desktop\sumo-master\sumo-master\src\activitygen\activitygen_main.cpp(35): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
17>c:\users\durraniu\desktop\sumo-master\sumo-master\src\marouter\marouter_main.cpp(32): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
11>Done building project "duarouter.vcxproj" -- FAILED.
16>Done building project "activitygen.vcxproj" -- FAILED.
17>Done building project "marouter.vcxproj" -- FAILED.
12>Done building project "dfrouter.vcxproj" -- FAILED.
14>guisim_main.cpp
14>c:\users\durraniu\desktop\sumo-master\sumo-master\src\guisim_main.cpp(32): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
13>Done building project "sumo.vcxproj" -- FAILED.
14>Done building project "sumo-gui.vcxproj" -- FAILED.
3>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netimport\niloader.cpp(65): fatal error C1083: Cannot open include file: 'typemap.h': No such file or directory
3>Done building project "y_libnetimport.vcxproj" -- FAILED.
18>------ Build started: Project: netconvert, Configuration: Release x64 ------
19>------ Build started: Project: netedit, Configuration: Release x64 ------
18>netconvert_main.cpp
19>GNEApplicationWindow.cpp
18>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netconvert_main.cpp(31): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
18>Done building project "netconvert.vcxproj" -- FAILED.
19>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netedit\gneapplicationwindow.cpp(29): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
19>netedit_main.cpp
19>c:\users\durraniu\desktop\sumo-master\sumo-master\src\netedit\netedit_main.cpp(29): fatal error C1083: Cannot open include file: 'version.h': No such file or directory
19>Done building project "netedit.vcxproj" -- FAILED.
========== Build: 0 succeeded, 19 failed, 45 up-to-date, 0 skipped ==========
`

**Comment by namdre** [comment]
python needs to be installed in order to create version.h

**Comment by durraniu** [comment]
I have python installed. I fact, I just re-built an older development version (downloaded 2 days ago) and got no problems. But re-building the latest one gives error: `c:\users\durraniu\desktop\sumo-master\sumo-master\src\gui\guiapplicationwindow.cpp(32): fatal error C1083: Cannot open include file: 'version.h': No such file or directory`

**Comment by namdre** [comment]
please run sumo/tools/build/version.py and check whether that solves the problem.

**Comment by durraniu** [comment]
Thanks. I executed `version.py `and it solved part of the errors. Now, I get following output: 

```
1>------ Build started: Project: z_libmicrosim_cfmodels, Configuration: Release x64 ------
2>------ Build started: Project: polyconvert, Configuration: Release x64 ------
1>MSCFModel_Wiedemann.cpp
2>polyconvert_main.cpp
2>c:\users\durraniu\desktop\sumo-master\sumo-master\src\polyconvert\polyconvert_main.cpp(61): fatal error C1083: Cannot open include file: 'pc_typemap.h': No such file or directory
2>Done building project "polyconvert.vcxproj" -- FAILED.
1>z_libmicrosim_cfmodels.vcxproj -> C:\Users\durraniu\Desktop\sumo-master\sumo-master\build\msvc10\z_libmicrosim_cfmodels\x64\Release\z_libmicrosim_cfmodels.lib
3>------ Build started: Project: sumo-gui, Configuration: Release x64 ------
4>------ Build started: Project: sumo, Configuration: Release x64 ------
4>Generating code
3>Generating code
4>Finished generating code
4>sumo.vcxproj -> C:\Users\durraniu\Desktop\sumo-master\sumo-master\build\msvc10\sumo\x64\Release\sumo.exe
4>C:\Users\durraniu\Desktop\sumo-master\sumo-master\build\msvc10\sumo\x64\Release\sumo.exe
4>1 File(s) copied
3>Finished generating code
3>sumo-gui.vcxproj -> C:\Users\durraniu\Desktop\sumo-master\sumo-master\build\msvc10\sumo-gui\x64\Release\sumo-gui.exe
3>C:\Users\durraniu\Desktop\sumo-master\sumo-master\build\msvc10\sumo-gui\x64\Release\sumo-gui.exe
3>1 File(s) copied
========== Build: 3 succeeded, 1 failed, 60 up-to-date, 0 skipped ==========
```  
I also ran `typemap.py` separately and tried re-building but still get the above message.

**Comment by namdre** [comment]
typemap.py must be called twice (to generate two different typemaps):
python typemap.py
python typemap.py 1

**Comment by durraniu** [comment]
Thank you. The issue was fixed after installation from the nightly build. For some reason the `version` and `typemap` files were not opening before.
