### ISSUE TITLE
traci `getCollidingVehiclesIDList` not returning colliding vehicle

### ISSUE THREAD

**Issue by c433li** [DLR-TS/sumo#3968]
traci `getCollidingVehiclesIDList` not returning colliding vehicle when is "--collision.action" set to "none".
Not sure if it's a deliberate design choice, but I think it's useful to correctly return `getCollidingVehiclesIDList` even when no action needs to be taken during collision.

**Comment by namdre** [comment]
collision.action none is meant to save the computational overhead of collision checking. If you want no action to be taken but collisions registered, select action 'warn'.
