### ISSUE TITLE
add comment attribute which is ignored by the binary formatter (trac #997)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#997]
It should be possible to have (write-only) attributes which are meant for human consumption but excluded in binary formats.

Right now something link this is possible when specifying (unknown) attr names as strings but this is less explicit.

One usage scenario is adding lane- and segment-ids when outputting simulation state.xml (which are technically not needed and would needlessly increase the size of state.sbx)

A possible implementation is to remove the inverse lookup when writing attributes using strings. Before doing so, the existing code needs to be checked whether it uses the lookup in critical places.

Migrated from http://sumo.dlr.de/ticket/997
```json
{
    "status": "new", 
    "changetime": "2014-03-07T11:47:30Z", 
    "description": "It should be possible to have (write-only) attributes which are meant for human consumption but excluded in binary formats.\n\nRight now something link this is possible when specifying (unknown) attr names as strings but this is less explicit.\n\nOne usage scenario is adding lane- and segment-ids when outputting simulation state.xml (which are technically not needed and would needlessly increase the size of state.sbx)\n\nA possible implementation is to remove the inverse lookup when writing attributes using strings. Before doing so, the existing code needs to be checked whether it uses the lookup in critical places.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1394192850786112", 
    "component": "simulation data output", 
    "summary": "add comment attribute which is ignored by the binary formatter", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2013-08-19T10:29:21Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
OutputFormatter now supports adding a comment when closing a tag.
